import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  const { data, error, isLoading } = trpc.example.hello.useQuery();
  if (isLoading) {
    return <p>Loading...</p>;
  }
  if (error) {
    return <div>{JSON.stringify(error)}</div>;
  }

  return (
    <>
      <Head>
        <title>Blog with T3 stack</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="text-4xl text-white">
          {JSON.stringify(data.greeting)}
        </div>
      </main>
    </>
  );
};

export default Home;
