import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import LoginForm from "../components/LoginForm";
import { useUserContext } from "../context/user.context";

const Home: NextPage = () => {
  const user = useUserContext();

  if (!user) {
    return <LoginForm />;
  }

  return (
    <>
      <Head>
        <title>Blog with T3 stack</title>

        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c] text-center">
        <Link href="/posts/new" className="text-white">
          Create post
        </Link>
      </main>
    </>
  );
};

export default Home;
